kedacore/http-add-on

README.md
docs/install.md
docs/walkthrough.md

Adding a walkthrough document for getting started
Fixes #17

Adding a walkthrough document

---

.github/CODEOWNERS

adding arschles as a codeowner

---

.github/workflows/build_canary.yml
.github/workflows/build_release.yml

Only pushing canary/sha images on pushes to main (not PRs)

---

README.md
docs/faq.md

Adding an FAQ document with answers to a few questions about how KEDA-HTTP is different from other similar projects.
Fixes https://github.com/kedacore/http-add-on/issues/59
Fixes https://github.com/kedacore/http-add-on/issues/58
Fixes https://github.com/kedacore/http-add-on/issues/57

Adding an FAQ

---

.github/workflows/build_canary.yml

workflow-fix

---

README.md
docs/faq.md
docs/scope.md

This PR adds a document that outlines the scope of functionality this project covers, for use in setting expectations and guiding future feature decisions.
Fixes #80

Adding documentation on the scope of functionality

---

README.md

This PR adds a brief intro section to the README
cc/ @tomkerkhove

adding a short intro section to the README

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR updates the issue, PR, and feature request templates to request specific information more clearly from the submitter.
Fixes #190

Updating the issue, PR and feature request templates

---

docs/install.md

This patch fixes a few small issues with the install.md document
Fixes #

Small issues with install.md

---

.github/ISSUE_TEMPLATE/config.yml

Allow blank issues for non-feature requests/bugs
- ~[ ] Any necessary documentation is added, such as:~

chore: Allow blank issues

---

.github/workflows/auto-add-issues-to-project.yml

Provide workflow to automatically add all issues to GitHub Project

feat: Provide workflow to automatically add all issues to GitHub Project

---

.github/ISSUE_TEMPLATE/bug_report.yaml
CONTRIBUTING.md
README.md
RELEASE-PROCESS.md
docs/design.md
docs/developing.md
docs/install.md
docs/ref/v0.1.0/http_scaled_object.md
docs/ref/v0.2.0/http_scaled_object.md
docs/scope.md
docs/use_cases.md
docs/walkthrough.md

Signed-off-by: Aaron Wislang <aaron.wislang@microsoft.com>
Updates all KEDA HTTP Add-on references to "HTTP Add-on" or "add-on" for consistency.

Update all references to HTTP Add-on / add-on

---

ADOPTERS.md
README.md

docs: Provide capability to become listed end-users

---

README.md

HTTP add-on is on hold and looking for contributors, see https://github.com/kedacore/http-add-on/discussions/523

docs: HTTP add-on is on hold and looking for contributors

---

docs/design.md
docs/developing.md
docs/faq.md
docs/install.md
docs/scope.md
docs/use_cases.md
docs/walkthrough.md

Signed-off-by: Jorge Turrado <jorge.turrado@scrm.lidl>

use relative links for going back

---

.github/PULL_REQUEST_TEMPLATE.md
Changelog.md

Introduce changelog to keep track of changes per release.
Closes https://github.com/kedacore/http-add-on/issues/591

chore: Introduce changelog

---

RELEASE-PROCESS.md

chore: Add Artifact Hub to release process

---

.github/workflows/auto-add-issues-to-project.yml

This is based on https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

fix(automation): Automatically add new issues to GitHub Project

---

.github/workflows/auto-add-issues-to-project.yml

Use GA API of GitHub Projects - https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/#%F0%9F%A4%96-graphql-api-improvements

fix(automation): Automatically add new issues to GitHub Project (#614

---

README.md

Proposal to provide update on project status.

chore: Provide update on project status (#628

---

config/scaler/kustomization.yaml
tests/e2e-test.sh

fix: Use correct labels during e2e tests

---

Makefile
hack/verify-manifests.sh

fix: Verify manifest changes correctly

---

.github/stale.yml

chore: Align stalebot ignore label with core

---

README.md

KEDA is a CNCF Graduated project.
Relates to https://github.com/kedacore/governance/issues/63

chore: KEDA is a CNCF Graduated project

---

hack/validate-changelog.sh

fix: Changelog validation script works again

---

interceptor/proxy_handlers.go

doc: correct the sentence structure

---

.devcontainer/Dockerfile
.github/workflows/build_canary.yml
.github/workflows/build_release.yml
.github/workflows/images.yaml
.github/workflows/tests.yaml
go.mod
go.sum
interceptor/Dockerfile
operator/Dockerfile
scaler/Dockerfile

chore: bump deps

---

.github/workflows/e2e-tests.yaml
.github/workflows/images.yaml
.github/workflows/linkinator.yaml
.github/workflows/tests.yaml
CHANGELOG.md

chore: Enable concuncurrency in PR workflows to skip unnecessary executions

---

.github/ISSUE_TEMPLATE/2_bug_report.yml
.github/workflows/e2e-tests.yaml
CHANGELOG.md
config/interceptor/deployment.yaml
config/scaler/deployment.yaml
docs/install.md
pkg/util/env_resolver.go
pkg/util/env_resolver_test.go
scaler/handlers.go

chore: Add missing changes for the release

---

.github/kind.yaml
.github/workflows/e2e-tests.yaml

chore: use in-memory kind for e2e tests

---

.github/workflows/build_release.yml

fix: Release uses correct repo

---

CHANGELOG.md
interceptor/middleware/routing.go
interceptor/middleware/routing_test.go

Add new probe user agent

---

scaler/config.go

chore: Remove not used var

---

docs/walkthrough.md

Fixes https://github.com/kedacore/http-add-on/issues/908

fix: Update walkthrough page with current steps

---

.github/workflows/e2e-tests.yaml

fix: Execute correct e2e test cases

---

ADOPTERS.md

Update ADOPTERS.md for PropulsionAI

---

docs/integrations.md
docs/readme.md

Added documentation for using keda http addon with istio in new file integrations.md. 

Add docs for integration of keda http addon with istio

---

docs/walkthrough.md

fix: use correct docs version

---

docs/walkthrough.md
examples/v0.8.0/httpscaledobject.yaml
examples/xkcd/templates/httpscaledobject.yaml

Fixes https://github.com/kedacore/http-add-on/issues/1026

chore: Add missing changes to examples

---

.github/ISSUE_TEMPLATE/2_bug_report.yml
.github/workflows/e2e-tests.yaml
docs/install.md

chore: Upgrade supported versions

---

docs/walkthrough.md

The original link is broken, causing the linter to fail

chore: use the correct link in the walkthrough doc

---

.github/workflows/build_canary.yml
.github/workflows/build_release.yml

Relates: https://github.com/kedacore/http-add-on/pull/1063

fix: propagate version to cosign in GH Actions

---

CHANGELOG.md
interceptor/middleware/routing.go
interceptor/middleware/routing_test.go

Add support for AWS ELB healthcheck probe #1198
Fixes #

add support for AWS ELB healthcheck probe #1198

---

.github/ISSUE_TEMPLATE/2_bug_report.yml
CHANGELOG.md
CONTRIBUTING.md
RELEASE-PROCESS.md
docs/ref/v0.9.0/http_scaled_object.md
docs/ref/vX.X.X/http_scaled_object.md
docs/walkthrough.md

Prepare release 0.9.0

---

examples/v0.9.0/httpscaledobject.yaml

This PR addresses issue #1236 by adding definition files for 0.9.0 version.
Fixes #1236

chore: add missing examples for 0.9.0

---

docs/install.md

Add KEDA and Kubernetes compatibility information for version 0.9.0.
Fixes #1246

Update compatibility documentation for v0.9.0

---

.github/workflows/linkinator.yaml

fix: ingnore Make link in the linkinator workflow

---

.github/ISSUE_TEMPLATE/2_bug_report.yml
.github/workflows/e2e-tests.yaml

chore: run e2e tests against k8s 1.32

---

scaler/handlers.go
scaler/handlers_test.go

Aligning the `GetMetricSpec` with `GetMetric`

chore: get the correct HTTPScaledObject reference in the scaler

---

CHANGELOG.md
docs/operate.md
interceptor/config/serving.go
interceptor/main.go
interceptor/main_test.go

feat(interceptor): Add possibility to skip tls verification for upstreams
